### ISSUE TITLE
Browser mod popup not working

### ISSUE THREAD

**Issue by K-RAD** [nutteloost/actions-card#1]
I'm trying to trigger a browser mod popup, but it doesn't seem to work

```
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      content:
        type: ....
```

**Comment by nutteloost** [comment]
Hi @K-RAD , in the [README](https://github.com/nutteloost/actions-card?tab=readme-ov-file#fire-dom-event-action) file you can find the correct configuration which the Actions card expects for the `fire-dom-event`.

The problem is with how you're structuring the fire-dom-event action. Here's what you have:
```yaml
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      content:
        type: ....
```

But the Actions Card's `fire-dom-event` action expects an event_type and optionally `event_data`. For `browser_mod` to work, you need to structure it like this:
```yaml
tap_action:
  action: fire-dom-event
  event_type: browser-mod
  event_data:
    service: browser_mod.popup
    data:
      title: "My Popup"
      content:
        type: entities
        entities:
          - light.living_room
```

This should work!
